name: Update weather-station

on:
  push:
    branches:
      - main
      - next
      - alpha

jobs:
  update-weather-station:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Update and restart services
        env:
          TAILNET_ADDESS: ${{ secrets.WEATHER_STATION_TAILNET_ADDRESS }}
          MARIADB_PASS: ${{ secrets.MARIADB_PASS }}
        # TODO: Call sudo systemctl daemon-reload if service files have changed
        run: |
          ssh -o "StrictHostKeyChecking no" pi@$TAILNET_ADDESS "
            cd weather-station && git fetch
            sudo systemctl restart weather-capture.service && sudo systemctl restart weather-api.service
            echo 'Restart command complete'
          "
          echo "Update complete"